name: Lint

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Golangci Lint
        uses: actions-contrib/golangci-lint@v1
        with:
          args: run --timeout=5m
        env:
          GOROOT: ""